project:
  title: "tidymodels for Production"
  output-dir: docs

format:
  revealjs:
    slide-number: true
    theme: [tidymodels.scss]
    width: 1280
    height: 720
    show-notes: false
    pdf-max-pages-per-slide: 1




knitr:
  opts_chunk:
    echo: true
    collapse: true
    comment: "#>"
    fig.path: "figures/"

fig-format: svg
